[package]
name = "RustyActixServer"
version = "0.1.0"
authors = ["Thomas John-Michael de Beer <tjdebeer@gmail.com.com>"]
edition = "2021"

[dependencies]
actix-web = "4.0.0"
actix-files = "0.6.0"
